<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="CShells.AspNetCore.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Authentication/ProgramKit.Authentication.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Authentication.SpaPkce/ProgramKit.Authentication.SpaPkce.csproj" />
  </ItemGroup>
</Project>
