<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Default Orbyss Forms definition validation and deterministic compilation to JSON Schema and JSON Forms UI Schema.</Description>
    <PackageId>Orbyss.Forms.JsonForms</PackageId>
    <PackageTags>orbyss-forms;forms;validation;json-schema;json-forms;compiler</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <ProjectReference Include="../Orbyss.Forms.Abstractions/Orbyss.Forms.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
