<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CShells.AspNetCore.Abstractions" />
    <PackageReference Include="Orbyss.Foundation.Mcp.AspNetCore" />
    <ProjectReference Include="../../../src/dotnet/Orbyss.Forms.Submissions/Orbyss.Forms.Submissions.csproj" />
    <ProjectReference Include="../../../src/dotnet/Orbyss.Forms.Core/Orbyss.Forms.Core.csproj" />
    <ProjectReference Include="../../../src/dotnet/Orbyss.Forms.Storage.FileSystem/Orbyss.Forms.Storage.FileSystem.csproj" />
    <ProjectReference Include="../../../src/dotnet/Orbyss.Forms.Tool/Orbyss.Forms.Tool.csproj" />
    <ProjectReference Include="../../../src/dotnet/Orbyss.Forms.Mcp.AspNetCore/Orbyss.Forms.Mcp.AspNetCore.csproj" />
    <ProjectReference Include="../../../src/dotnet/Orbyss.Forms.Web.Submissions/Orbyss.Forms.Web.Submissions.csproj" />
  </ItemGroup>
</Project>
