<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Forms.Abstractions/ProgramKit.Forms.Abstractions.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Forms.Core/ProgramKit.Forms.Core.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Forms.JsonForms/ProgramKit.Forms.JsonForms.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Forms.Localization/ProgramKit.Forms.Localization.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Forms.Storage.FileSystem/ProgramKit.Forms.Storage.FileSystem.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Localization.Abstractions/ProgramKit.Localization.Abstractions.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Localization.Application/ProgramKit.Localization.Application.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Localization.Core/ProgramKit.Localization.Core.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Localization.Formats/ProgramKit.Localization.Formats.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Localization.Storage.FileSystem/ProgramKit.Localization.Storage.FileSystem.csproj" />
  </ItemGroup>
</Project>
