<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CShells.AspNetCore.Abstractions" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Localization.Core/ProgramKit.Localization.Core.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Localization.Formats/ProgramKit.Localization.Formats.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Localization.Web.Management/ProgramKit.Localization.Web.Management.csproj" />
    <ProjectReference Include="../../../src/dotnet/ProgramKit.Localization.Web.Runtime/ProgramKit.Localization.Web.Runtime.csproj" />
  </ItemGroup>
</Project>
