import { NgTemplateOutlet } from "@angular/common";
import { ChangeDetectionStrategy, Component, ElementRef, EventEmitter, Input, Output, TemplateRef, ViewChild, type AfterViewChecked, type OnDestroy, type OnInit } from "@angular/core";
import { codeMirrorJsonEditorAdapter } from "@orbyss/program-kit-forms-codemirror";
import type { JsonEditorAdapter, JsonEditorHandle } from "@orbyss/program-kit-forms-editor-contracts";
import {
  getFormModelerElementPlacement,
  listFormModelerMoveTargets,
  parseFormModelerDocument,
  projectFormModelerGraph,
  serializeFormModelerDocument,
  type FormModelerAction,
  type FormModelerActionCatalog,
  type FormModelerComponentCatalog,
  type FormModelerComponentContract,
  type FormModelerDocument,
  type FormModelerElement,
  type FormModelerField,
  type FormModelerOperation,
  type FormModelerSession,
  type FormModelerSnapshot
} from "@orbyss/program-kit-forms-modeler";
import { programKitClassName, type ProgramKitClassNames } from "@orbyss/program-kit-ui-theme";

export type FormModelerAngularView = "design" | "json" | "graph";
export type FormModelerAngularEditorMode = "rich" | "strictCsp";
export type FormModelerAngularThemeSlot = "root" | "toolbar" | "diagnostics" | "tabs" | "workspace" | "design" | "palette" | "tree" | "canvas" | "preview" | "inspector" | "panel" | "editor" | "graph" | "graphNode" | "canvasBlock";
export type FormModelerAngularPaletteItem = { readonly id: string; readonly label: string; readonly category: string; readonly type: "field"; readonly valueKind: FormModelerField["valueKind"] } | { readonly id: string; readonly label: string; readonly category: string; readonly type: "element"; readonly elementKind: "group" | "horizontalLayout" | "verticalLayout" | "text" };
export const defaultFormModelerAngularPalette: readonly FormModelerAngularPaletteItem[] = Object.freeze([
  { id: "text-field", label: "Add text field", category: "Fields", type: "field", valueKind: "string" }, { id: "number-field", label: "Add number field", category: "Fields", type: "field", valueKind: "number" }, { id: "boolean-field", label: "Add yes/no field", category: "Fields", type: "field", valueKind: "boolean" },
  { id: "group", label: "Add group", category: "Layout", type: "element", elementKind: "group" }, { id: "horizontal-layout", label: "Add horizontal layout", category: "Layout", type: "element", elementKind: "horizontalLayout" }, { id: "vertical-layout", label: "Add vertical layout", category: "Layout", type: "element", elementKind: "verticalLayout" }, { id: "text", label: "Add explanatory text", category: "Content", type: "element", elementKind: "text" }
]);
export interface ProgramKitFormModelerAngularLabels { readonly undo: string; readonly redo: string; readonly commit: string; readonly applyJson: string; readonly design: string; readonly json: string; readonly graph: string; readonly structure: string; readonly inspector: string; readonly editor: string; readonly nodes: string; readonly relationships: string; readonly diagnostics: string; readonly palette: string; readonly canvas: string; readonly preview: string; readonly moveEarlier: string; readonly moveLater: string; readonly moveTo: string; }
const defaults: ProgramKitFormModelerAngularLabels = Object.freeze({ undo: "Undo", redo: "Redo", commit: "Commit changes", applyJson: "Apply JSON", design: "Design", json: "JSON", graph: "Graph", structure: "Form structure", inspector: "Properties", editor: "Form JSON", nodes: "Form nodes", relationships: "Relationships", diagnostics: "Modeler diagnostics", palette: "Component palette", canvas: "Layout canvas", preview: "Live preview", moveEarlier: "Move earlier", moveLater: "Move later", moveTo: "Move to" });
interface ElementPlacement { readonly element: FormModelerElement; readonly parentId?: string; readonly index: number; readonly siblingCount: number; }

@Component({
  selector: "program-kit-form-modeler",
  standalone: true,
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
  <section [class]="slotClass('root', 'pk-form-modeler', className)" data-pk-slot="form-modeler.root" [attr.data-pk-unstyled]="unstyled || null">
    <div [class]="slotClass('toolbar', 'pk-form-modeler__toolbar')" data-pk-slot="form-modeler.toolbar" role="toolbar" aria-label="Modeler actions"><button type="button" [disabled]="!snapshot.canUndo" (click)="refresh(session.undo())">{{ text.undo }}</button><button type="button" [disabled]="!snapshot.canRedo" (click)="refresh(session.redo())">{{ text.redo }}</button><button type="button" [disabled]="bindingDiagnostics().length > 0" (click)="commit.emit({ document: snapshot.document, sequence: snapshot.sequence })">{{ text.commit }}</button></div>
    @if (error || bindingDiagnostics().length > 0) { <div [class]="slotClass('diagnostics', 'pk-form-modeler__diagnostics')" data-pk-slot="form-modeler.diagnostics" role="alert" [attr.aria-label]="text.diagnostics">@if (error) { <p>{{ error }}</p> } @for (item of bindingDiagnostics(); track item.code + item.path) { <p>{{ item.message }}</p> }</div> }
    <div [class]="slotClass('tabs', 'pk-form-modeler__tabs')" data-pk-slot="form-modeler.tabs" role="tablist" aria-label="Modeler views">@for (candidate of views; track candidate) { <button type="button" role="tab" [attr.aria-selected]="view === candidate" (click)="setView(candidate)">{{ viewLabel(candidate) }}</button> }</div>
    @if (view === 'design') { <section [class]="slotClass('workspace', 'pk-form-modeler__workspace')" data-pk-slot="form-modeler.workspace" role="tabpanel">
      <aside [class]="slotClass('palette', 'pk-form-modeler__palette')" data-pk-slot="form-modeler.palette" [attr.aria-label]="text.palette"><h2>{{ text.palette }}</h2>@for (category of categories(); track category) { <section><h3>{{ category }}</h3><div>@for (item of paletteFor(category); track item.id) { <button type="button" (click)="add(item)">{{ item.label }}</button> }</div></section> }</aside>
      <div [class]="slotClass('design', 'pk-form-modeler__design')" data-pk-slot="form-modeler.design"><nav [class]="slotClass('tree', 'pk-form-modeler__tree')" data-pk-slot="form-modeler.tree" [attr.aria-label]="text.structure"><ul><li><button type="button" [attr.aria-current]="snapshot.selectedId === snapshot.document.id" (click)="select(snapshot.document.id)">{{ snapshot.document.name }}</button></li><li><span>Fields</span><ul>@for (field of snapshot.document.fields; track field.id) { <li><button type="button" [attr.aria-current]="snapshot.selectedId === field.id" (click)="select(field.id)">{{ field.label.defaultText }}</button></li> }</ul></li><li><span>Layout</span><ul>@for (entry of elements(); track entry.element.id) { <li><button type="button" [attr.aria-current]="snapshot.selectedId === entry.element.id" (click)="select(entry.element.id)">{{ entry.element.id }} · {{ entry.element.kind }}</button></li> }</ul></li><li><span>Actions</span><ul>@for (action of snapshot.document.actions; track action.id) { <li><button type="button" [attr.aria-current]="snapshot.selectedId === action.id" (click)="select(action.id)">{{ action.label.defaultText }}</button></li> }</ul></li></ul></nav>
        <section [class]="slotClass('canvas', 'pk-form-modeler__canvas')" data-pk-slot="form-modeler.canvas" [attr.aria-label]="text.canvas"><h2>{{ text.canvas }}</h2>@for (entry of elements(); track entry.element.id) { <div [class]="slotClass('canvasBlock', 'pk-form-modeler__canvas-block')" data-pk-slot="form-modeler.canvasBlock" [attr.data-element-id]="entry.element.id" [attr.data-kind]="entry.element.kind" [attr.draggable]="entry.parentId ? true : null" (dragstart)="startDrag(entry.element.id, $event)" (dragover)="allowDrop($event)" (drop)="dropBefore(entry, $event)"><div class="pk-form-modeler__canvas-heading"><button type="button" [attr.aria-pressed]="snapshot.selectedId === entry.element.id" (click)="select(entry.element.id)"><strong>{{ elementLabel(entry.element) }}</strong><small>{{ entry.element.kind }}</small></button>@if (entry.parentId) { <div class="pk-form-modeler__reorder" role="group" [attr.aria-label]="'Reorder ' + elementLabel(entry.element)"><button type="button" [attr.aria-label]="text.moveEarlier + ': ' + elementLabel(entry.element)" [disabled]="entry.index === 0" (click)="move(entry.element.id, entry.parentId, entry.index - 1)">↑</button><button type="button" [attr.aria-label]="text.moveLater + ': ' + elementLabel(entry.element)" [disabled]="entry.index >= entry.siblingCount - 1" (click)="move(entry.element.id, entry.parentId, entry.index + 1)">↓</button></div> }</div></div> }</section>
        <section [class]="slotClass('preview', 'pk-form-modeler__preview')" data-pk-slot="form-modeler.preview" [attr.aria-label]="text.preview"><h2>{{ text.preview }}</h2>@if (previewTemplate) { <ng-container *ngTemplateOutlet="previewTemplate; context: { $implicit: snapshot.document }"></ng-container> } @else { <p>{{ snapshot.document.fields.length }} fields · {{ elements().length }} layout blocks</p> }</section></div>
      <aside [class]="slotClass('inspector', 'pk-form-modeler__inspector')" data-pk-slot="form-modeler.inspector" [attr.aria-label]="text.inspector"><h2>{{ text.inspector }}</h2>
        @if (selectedField(); as field) { <h3>{{ field.id }}</h3><label class="pk-form-modeler__field">Label<input [value]="field.label.defaultText" (change)="updateField(field, { label: localized(field, value($event)) })"></label><label><input type="checkbox" [checked]="field.required" (change)="updateField(field, { required: checked($event) })"> Required</label>@if (componentCatalog) { <label class="pk-form-modeler__field">Component<select [value]="field.component?.componentId || ''" (change)="chooseComponent(field, value($event))"><option value="">Default renderer</option>@for (contract of componentsFor(field); track contract.componentId) { <option [value]="contract.componentId">{{ contract.displayName }}</option> }</select></label> } @if (selectedComponent(field); as contract) { <div class="pk-form-modeler__component"><p>{{ contract.description || contract.displayName }}</p><dl><dt>Package</dt><dd>{{ contract.providerPackage || 'Application-owned' }}</dd><dt>Compatible version</dt><dd>{{ contract.versionRange }}</dd></dl>@for (option of contract.options || []; track option.key) { <label class="pk-form-modeler__field">{{ option.displayName }}@if (option.kind === 'choice' || option.kind === 'boolean') { <select [value]="componentOption(field, option.key, option.defaultValue)" [required]="option.required" (change)="updateOption(field, option.key, value($event))"><option value="" [disabled]="option.required">Select</option>@for (choice of optionChoices(option); track choice.value) { <option [value]="choice.value">{{ choice.label }}</option> }</select> } @else { <input [value]="componentOption(field, option.key, option.defaultValue)" [required]="option.required" (input)="updateOption(field, option.key, value($event))"> }</label> }</div> }<dl><dt>Data path</dt><dd>{{ field.dataPath }}</dd><dt>Value kind</dt><dd>{{ field.valueKind }}</dd></dl>
        } @else if (selectedAction(); as action) { <h3>{{ action.label.defaultText }}</h3><dl><dt>Handler</dt><dd>{{ action.handlerId }}</dd><dt>Execution</dt><dd>{{ actionContract(action)?.execution || 'Unregistered' }}</dd><dt>Package</dt><dd>{{ actionContract(action)?.providerPackage || 'Application-owned' }}</dd></dl>
        } @else if (selectedElement(); as element) { <h3>{{ element.id }}</h3><dl><dt>Kind</dt><dd>{{ element.kind }}</dd><dt>Children</dt><dd>{{ element.elements.length }}</dd></dl>@for (target of moveTargets(element); track target.parentId) { <button type="button" [disabled]="placement(element).parentId === target.parentId" (click)="move(element.id, target.parentId, target.maximumIndex)">{{ text.moveTo }} {{ target.label }}</button> }
        } @else { <h3>{{ snapshot.document.name }}</h3><dl><dt>ID</dt><dd>{{ snapshot.document.id }}</dd><dt>Revision</dt><dd>{{ snapshot.document.revision }}</dd><dt>Source locale</dt><dd>{{ snapshot.document.sourceLocale }}</dd></dl> }
      </aside></section> }
    @if (view === 'json') { <section [class]="slotClass('panel', 'pk-form-modeler__panel')" data-pk-slot="form-modeler.panel" role="tabpanel"><div #editorHost [hidden]="editorMode === 'strictCsp'" [class]="slotClass('editor', 'pk-form-modeler__editor')" data-pk-slot="form-modeler.editor"></div>@if (editorMode === 'strictCsp') { <textarea [class]="slotClass('editor', 'pk-form-modeler__editor pk-form-modeler__editor--strict-csp')" data-pk-slot="form-modeler.editor" [attr.aria-label]="text.editor" [value]="source" spellcheck="false" (input)="source = value($event)"></textarea> }<button type="button" (click)="applySource()">{{ text.applyJson }}</button></section> }
    @if (view === 'graph') { <section [class]="slotClass('graph', 'pk-form-modeler__panel')" data-pk-slot="form-modeler.graph" role="tabpanel"><h2>{{ text.nodes }}</h2><div class="pk-form-modeler__graph-nodes">@for (node of graph().nodes; track node.id) { <button type="button" [class]="slotClass('graphNode', 'pk-form-modeler__graph-node')" data-pk-slot="form-modeler.graphNode" (click)="select(rawGraphId(node.id))"><strong>{{ node.label }}</strong><small>{{ node.kind }}</small></button> }</div><h2>{{ text.relationships }}</h2><table class="pk-form-modeler__graph-edges"><thead><tr><th>From</th><th>Relationship</th><th>To</th></tr></thead><tbody>@for (edge of graph().edges; track edge.from + edge.to) { <tr><td>{{ edge.from }}</td><td>{{ edge.kind }}</td><td>{{ edge.to }}</td></tr> }</tbody></table></section> }
  </section>`
})
export class ProgramKitFormModelerAngularComponent implements OnInit, AfterViewChecked, OnDestroy {
  @Input({ required: true }) session!: FormModelerSession; @Input() initialView: FormModelerAngularView = "design"; @Input() labels: Partial<ProgramKitFormModelerAngularLabels> = {};
  @Input() actionCatalog?: FormModelerActionCatalog; @Input() componentCatalog?: FormModelerComponentCatalog; @Input() paletteItems: readonly FormModelerAngularPaletteItem[] = defaultFormModelerAngularPalette;
  @Input() previewTemplate?: TemplateRef<{ $implicit: FormModelerDocument }>; @Input() editorMode: FormModelerAngularEditorMode = "rich"; @Input() editorAdapter: JsonEditorAdapter = codeMirrorJsonEditorAdapter; @Input() cspNonce?: string;
  @Input() classNames: ProgramKitClassNames<FormModelerAngularThemeSlot> = {}; @Input() className?: string; @Input() unstyled = false;
  @Output() readonly change = new EventEmitter<FormModelerSnapshot>(); @Output() readonly commit = new EventEmitter<{ readonly document: FormModelerDocument; readonly sequence: number }>(); @ViewChild("editorHost") editorHost?: ElementRef<HTMLElement>;
  readonly views: readonly FormModelerAngularView[] = ["design", "json", "graph"]; snapshot!: FormModelerSnapshot; view: FormModelerAngularView = "design"; source = ""; error = ""; draggingId: string | undefined;
  private editor: JsonEditorHandle | undefined; private editorElement: HTMLElement | undefined; private command = 1;
  get text(): ProgramKitFormModelerAngularLabels { return { ...defaults, ...this.labels }; }
  ngOnInit(): void { this.view = this.initialView; this.snapshot = this.session.snapshot(); this.source = serializeFormModelerDocument(this.snapshot.document); }
  ngAfterViewChecked(): void { const host = this.view === "json" && this.editorMode === "rich" ? this.editorHost?.nativeElement : undefined; if (host === this.editorElement) return; this.destroyEditor(); if (host !== undefined) { this.editorElement = host; this.editor = this.editorAdapter.mount({ parent: host, document: this.source, accessibleLabel: this.text.editor, onChange: value => { this.source = value; }, diagnostics: value => { try { parseFormModelerDocument(value); return []; } catch (reason) { return [{ from: 0, to: value.length, severity: "error", message: publicError(reason) }]; } }, ...(this.cspNonce === undefined ? {} : { cspNonce: this.cspNonce }) }); } }
  ngOnDestroy(): void { this.destroyEditor(); }
  slotClass(name: FormModelerAngularThemeSlot, base: string, extra?: string): string | undefined { return programKitClassName(base, [this.classNames[name], extra].filter(Boolean).join(" ") || undefined, this.unstyled); }
  viewLabel(view: FormModelerAngularView): string { return this.text[view]; } setView(view: FormModelerAngularView): void { this.view = view; if (view !== "json") this.destroyEditor(); }
  refresh(next: FormModelerSnapshot): void { this.snapshot = next; this.source = serializeFormModelerDocument(next.document); this.editor?.setDocument(this.source); this.error = ""; this.change.emit(next); }
  apply(operations: readonly FormModelerOperation[]): boolean { try { this.refresh(this.session.apply({ commandId: `form-angular:${this.snapshot.sequence}:${this.command++}`, expectedSequence: this.snapshot.sequence, operations })); return true; } catch (reason) { this.error = publicError(reason); return false; } }
  applySource(): void { try { this.apply([{ type: "replaceDocument", document: parseFormModelerDocument(this.source) }]); } catch (reason) { this.error = publicError(reason); } }
  select(id: string): void { this.refresh(this.session.select(id)); } bindingDiagnostics() { return [...(this.actionCatalog?.validateBindings(this.snapshot.document.actions) ?? []), ...(this.componentCatalog?.validateBindings(this.snapshot.document.fields) ?? [])]; }
  categories(): readonly string[] { return [...new Set(this.paletteItems.map(item => item.category))]; } paletteFor(category: string): readonly FormModelerAngularPaletteItem[] { return this.paletteItems.filter(item => item.category === category); }
  add(item: FormModelerAngularPaletteItem): void { const addition = createPaletteAddition(this.snapshot.document, this.snapshot.selectedId, item); if (this.apply(addition.operations)) this.select(addition.selectedId); }
  elements(): readonly ElementPlacement[] { const result: ElementPlacement[] = []; const visit = (element: FormModelerElement, parentId?: string, index = 0, siblingCount = 1) => { result.push({ element, ...(parentId === undefined ? {} : { parentId }), index, siblingCount }); element.elements.forEach((child, childIndex) => visit(child, element.id, childIndex, element.elements.length)); }; visit(this.snapshot.document.layout); return result; }
  elementLabel(element: FormModelerElement): string { const field = element.fieldId == null ? undefined : this.snapshot.document.fields.find(item => item.id === element.fieldId); return field?.label.defaultText ?? element.text?.defaultText ?? element.id; }
  selectedField(): FormModelerField | undefined { return this.snapshot.document.fields.find(item => item.id === this.snapshot.selectedId); } selectedAction(): FormModelerAction | undefined { return this.snapshot.document.actions.find(item => item.id === this.snapshot.selectedId); } selectedElement(): FormModelerElement | undefined { return this.elements().find(item => item.element.id === this.snapshot.selectedId)?.element; }
  updateField(field: FormModelerField, changes: Partial<FormModelerField>): void { this.apply([{ type: "upsertField", field: { ...field, ...changes } }]); } localized(field: FormModelerField, text: string) { return { ...field.label, defaultText: text }; }
  componentsFor(field: FormModelerField): readonly FormModelerComponentContract[] { return this.componentCatalog?.listFor(field.valueKind) ?? []; } selectedComponent(field: FormModelerField): FormModelerComponentContract | undefined { return field.component == null ? undefined : this.componentCatalog?.resolve(field.component.componentId); }
  chooseComponent(field: FormModelerField, id: string): void { this.updateField(field, { component: id.length === 0 ? null : this.componentCatalog?.createReference(id) ?? null }); } componentOption(field: FormModelerField, key: string, fallback?: string): string { return field.component?.options?.[key] ?? fallback ?? ""; }
  updateOption(field: FormModelerField, key: string, value: string): void { if (field.component != null) this.updateField(field, { component: { ...field.component, options: { ...field.component.options, [key]: value } } }); } optionChoices(option: NonNullable<FormModelerComponentContract["options"]>[number]) { return option.kind === "boolean" ? [{ value: "true", label: "Yes" }, { value: "false", label: "No" }] : option.choices ?? []; }
  actionContract(action: FormModelerAction) { return this.actionCatalog?.resolve(action.handlerId); } placement(element: FormModelerElement) { return getFormModelerElementPlacement(this.snapshot.document, element.id); } moveTargets(element: FormModelerElement) { return listFormModelerMoveTargets(this.snapshot.document, element.id); }
  move(elementId: string, parentId: string, index: number): void { const target = listFormModelerMoveTargets(this.snapshot.document, elementId).find(value => value.parentId === parentId); if (target !== undefined && index >= 0 && index <= target.maximumIndex) this.apply([{ type: "moveElement", elementId, parentId, index }]); }
  startDrag(id: string, event: DragEvent): void { this.draggingId = id; event.dataTransfer?.setData("application/x-program-kit-form-element", id); } allowDrop(event: DragEvent): void { if (this.draggingId !== undefined) event.preventDefault(); } dropBefore(entry: ElementPlacement, event: DragEvent): void { if (this.draggingId !== undefined && entry.parentId !== undefined && this.draggingId !== entry.element.id) { event.preventDefault(); this.move(this.draggingId, entry.parentId, entry.index); } this.draggingId = undefined; }
  graph(): ReturnType<typeof projectFormModelerGraph> { return projectFormModelerGraph(this.snapshot.document); } rawGraphId(id: string): string { return id.slice(id.indexOf(":") + 1); }
  value(event: Event): string { return (event.currentTarget as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement).value; } checked(event: Event): boolean { return (event.currentTarget as HTMLInputElement).checked; }
  private destroyEditor(): void { this.editor?.destroy(); this.editor = undefined; this.editorElement = undefined; }
}

function createPaletteAddition(document: FormModelerDocument, selectedId: string | undefined, item: FormModelerAngularPaletteItem): { readonly operations: readonly FormModelerOperation[]; readonly selectedId: string } { const selected = selectedId === undefined ? undefined : findElement(document.layout, selectedId); const parentId = selected !== undefined && containerKinds.has(selected.kind) ? selected.id : document.layout.id; const index = findElement(document.layout, parentId)?.elements.length ?? 0; if (item.type === "field") { const fieldId = nextId(document, "field"); const field: FormModelerField = { id: fieldId, dataPath: `/${fieldId}`, valueKind: item.valueKind, required: false, label: { key: `fields.${fieldId}`, defaultText: `Field ${fieldId.slice(6)}` } }; const controlId = nextId(document, `${fieldId}-control`); return { operations: [{ type: "upsertField", field }, { type: "insertElement", parentId, index, element: { id: controlId, kind: "control", fieldId, elements: [] } }], selectedId: fieldId }; } const prefix = item.elementKind.replace(/[A-Z]/g, value => `-${value.toLowerCase()}`); const id = nextId(document, prefix); return { operations: [{ type: "insertElement", parentId, index, element: { id, kind: item.elementKind, elements: [], ...(item.elementKind === "text" ? { text: { key: `content.${id}`, defaultText: "Explanatory text" } } : {}) } }], selectedId: id }; }
function findElement(element: FormModelerElement, id: string): FormModelerElement | undefined { if (element.id === id) return element; for (const child of element.elements) { const value = findElement(child, id); if (value !== undefined) return value; } return undefined; }
function nextId(document: FormModelerDocument, prefix: string): string { const ids = new Set([document.id, ...document.fields.map(item => item.id), ...document.actions.map(item => item.id)]); const visit = (element: FormModelerElement) => { ids.add(element.id); element.elements.forEach(visit); }; visit(document.layout); let value = 1; while (ids.has(`${prefix}-${value}`)) value += 1; return `${prefix}-${value}`; }
function publicError(reason: unknown): string { return reason instanceof Error ? reason.message : "The form operation could not be completed."; }
const containerKinds = new Set<FormModelerElement["kind"]>(["group", "horizontalLayout", "verticalLayout", "wizard", "step"]);
